// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://fbhjsxikcmtfimjmgzcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiaGpzeGlrY210Zmltam1nemN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzQ3OTYsImV4cCI6MjA3MDIxMDc5Nn0.BiWD_B5QbM_uQCA0TrpWZG4LbfeAlA5wTY3SGuKa5JY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});